### PR TITLE
upgrade to bootstrap 4.4

### PR DESCRIPTION
**Pull request by ahmednoureldeen**

### CODE REVIEW

**Comment by slead** [comment]
@ahmednoureldeen this is fantastic, thanks so much for making these changes. There are a few more changes required in the Query widget which I'll make before pushing it live.

Screen Shot 2019-11-29 at 11 28 44 am

**Comment by ahmednoureldeen** [comment]
@slead here you are the missing part, but the default style is a little bit different

**Comment by ahmednoureldeen** [comment]
@slead can we proceed with this

**Comment by slead** [comment]
@ahmednoureldeen many thanks for making these changes, it looks great. There is a minor issue with the symbols for sorting the data tables, which I haven't had a chance to look into yet. Feel free to update these if you have time

Bootstrap 3:

Screen Shot 2019-12-06 at 12 17 01 pm

Bootstrap 4:

Screen Shot 2019-12-06 at 12 17 39 pm

**Pull request merged**
